/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as LandingLayoutImport } from './routes/~_landing-layout'
import { Route as LandingLayoutIndexImport } from './routes/~_landing-layout.index'
import { Route as coreAuthenticatedLayoutImport } from './routes/~(core)/~_authenticated-layout'
import { Route as authSignUpImport } from './routes/~(auth)/~sign-up'
import { Route as authSignInImport } from './routes/~(auth)/~sign-in'
import { Route as coreAuthenticatedLayoutDashboardDocumentsImport } from './routes/~(core)/~_authenticated-layout/~dashboard/~documents'
import { Route as coreAuthenticatedLayoutDashboardIndexImport } from './routes/~(core)/~_authenticated-layout/~dashboard/~index'
import { Route as coreAuthenticatedLayoutDashboardDocumentDocumentIdEditImport } from './routes/~(core)/~_authenticated-layout/~dashboard/~document/~$document-id/~edit'

// Create Virtual Routes

const coreImport = createFileRoute('/(core)')()

// Create/Update Routes

const coreRoute = coreImport.update({
  id: '/(core)',
  getParentRoute: () => rootRoute,
} as any)

const LandingLayoutRoute = LandingLayoutImport.update({
  id: '/_landing-layout',
  getParentRoute: () => rootRoute,
} as any)

const LandingLayoutIndexRoute = LandingLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingLayoutRoute,
} as any)

const coreAuthenticatedLayoutRoute = coreAuthenticatedLayoutImport.update({
  id: '/_authenticated-layout',
  getParentRoute: () => coreRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const coreAuthenticatedLayoutDashboardDocumentsRoute =
  coreAuthenticatedLayoutDashboardDocumentsImport.update({
    id: '/dashboard/documents',
    path: '/dashboard/documents',
    getParentRoute: () => coreAuthenticatedLayoutRoute,
  } as any)

const coreAuthenticatedLayoutDashboardIndexRoute =
  coreAuthenticatedLayoutDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => coreAuthenticatedLayoutRoute,
  } as any)

const coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute =
  coreAuthenticatedLayoutDashboardDocumentDocumentIdEditImport.update({
    id: '/dashboard/document/$document-id/edit',
    path: '/dashboard/document/$document-id/edit',
    getParentRoute: () => coreAuthenticatedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing-layout': {
      id: '/_landing-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(core)': {
      id: '/(core)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreImport
      parentRoute: typeof rootRoute
    }
    '/(core)/_authenticated-layout': {
      id: '/(core)/_authenticated-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreAuthenticatedLayoutImport
      parentRoute: typeof coreRoute
    }
    '/_landing-layout/': {
      id: '/_landing-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingLayoutIndexImport
      parentRoute: typeof LandingLayoutImport
    }
    '/(core)/_authenticated-layout/dashboard/': {
      id: '/(core)/_authenticated-layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof coreAuthenticatedLayoutDashboardIndexImport
      parentRoute: typeof coreAuthenticatedLayoutImport
    }
    '/(core)/_authenticated-layout/dashboard/documents': {
      id: '/(core)/_authenticated-layout/dashboard/documents'
      path: '/dashboard/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof coreAuthenticatedLayoutDashboardDocumentsImport
      parentRoute: typeof coreAuthenticatedLayoutImport
    }
    '/(core)/_authenticated-layout/dashboard/document/$document-id/edit': {
      id: '/(core)/_authenticated-layout/dashboard/document/$document-id/edit'
      path: '/dashboard/document/$document-id/edit'
      fullPath: '/dashboard/document/$document-id/edit'
      preLoaderRoute: typeof coreAuthenticatedLayoutDashboardDocumentDocumentIdEditImport
      parentRoute: typeof coreAuthenticatedLayoutImport
    }
  }
}

// Create and export the route tree

interface LandingLayoutRouteChildren {
  LandingLayoutIndexRoute: typeof LandingLayoutIndexRoute
}

const LandingLayoutRouteChildren: LandingLayoutRouteChildren = {
  LandingLayoutIndexRoute: LandingLayoutIndexRoute,
}

const LandingLayoutRouteWithChildren = LandingLayoutRoute._addFileChildren(
  LandingLayoutRouteChildren,
)

interface coreAuthenticatedLayoutRouteChildren {
  coreAuthenticatedLayoutDashboardIndexRoute: typeof coreAuthenticatedLayoutDashboardIndexRoute
  coreAuthenticatedLayoutDashboardDocumentsRoute: typeof coreAuthenticatedLayoutDashboardDocumentsRoute
  coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute: typeof coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute
}

const coreAuthenticatedLayoutRouteChildren: coreAuthenticatedLayoutRouteChildren =
  {
    coreAuthenticatedLayoutDashboardIndexRoute:
      coreAuthenticatedLayoutDashboardIndexRoute,
    coreAuthenticatedLayoutDashboardDocumentsRoute:
      coreAuthenticatedLayoutDashboardDocumentsRoute,
    coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute:
      coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute,
  }

const coreAuthenticatedLayoutRouteWithChildren =
  coreAuthenticatedLayoutRoute._addFileChildren(
    coreAuthenticatedLayoutRouteChildren,
  )

interface coreRouteChildren {
  coreAuthenticatedLayoutRoute: typeof coreAuthenticatedLayoutRouteWithChildren
}

const coreRouteChildren: coreRouteChildren = {
  coreAuthenticatedLayoutRoute: coreAuthenticatedLayoutRouteWithChildren,
}

const coreRouteWithChildren = coreRoute._addFileChildren(coreRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LandingLayoutRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/': typeof LandingLayoutIndexRoute
  '/dashboard': typeof coreAuthenticatedLayoutDashboardIndexRoute
  '/dashboard/documents': typeof coreAuthenticatedLayoutDashboardDocumentsRoute
  '/dashboard/document/$document-id/edit': typeof coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute
}

export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/': typeof LandingLayoutIndexRoute
  '/dashboard': typeof coreAuthenticatedLayoutDashboardIndexRoute
  '/dashboard/documents': typeof coreAuthenticatedLayoutDashboardDocumentsRoute
  '/dashboard/document/$document-id/edit': typeof coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_landing-layout': typeof LandingLayoutRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(core)': typeof coreRouteWithChildren
  '/(core)/_authenticated-layout': typeof coreAuthenticatedLayoutRouteWithChildren
  '/_landing-layout/': typeof LandingLayoutIndexRoute
  '/(core)/_authenticated-layout/dashboard/': typeof coreAuthenticatedLayoutDashboardIndexRoute
  '/(core)/_authenticated-layout/dashboard/documents': typeof coreAuthenticatedLayoutDashboardDocumentsRoute
  '/(core)/_authenticated-layout/dashboard/document/$document-id/edit': typeof coreAuthenticatedLayoutDashboardDocumentDocumentIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/dashboard'
    | '/dashboard/documents'
    | '/dashboard/document/$document-id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/dashboard'
    | '/dashboard/documents'
    | '/dashboard/document/$document-id/edit'
  id:
    | '__root__'
    | '/_landing-layout'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(core)'
    | '/(core)/_authenticated-layout'
    | '/_landing-layout/'
    | '/(core)/_authenticated-layout/dashboard/'
    | '/(core)/_authenticated-layout/dashboard/documents'
    | '/(core)/_authenticated-layout/dashboard/document/$document-id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LandingLayoutRoute: typeof LandingLayoutRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  coreRoute: typeof coreRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LandingLayoutRoute: LandingLayoutRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  coreRoute: coreRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/_landing-layout",
        "/(auth)/sign-in",
        "/(auth)/sign-up",
        "/(core)"
      ]
    },
    "/_landing-layout": {
      "filePath": "~_landing-layout.tsx",
      "children": [
        "/_landing-layout/"
      ]
    },
    "/(auth)/sign-in": {
      "filePath": "~(auth)/~sign-in.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "~(auth)/~sign-up.tsx"
    },
    "/(core)": {
      "filePath": "~(core)",
      "children": [
        "/(core)/_authenticated-layout"
      ]
    },
    "/(core)/_authenticated-layout": {
      "filePath": "~(core)/~_authenticated-layout.tsx",
      "parent": "/(core)",
      "children": [
        "/(core)/_authenticated-layout/dashboard/",
        "/(core)/_authenticated-layout/dashboard/documents",
        "/(core)/_authenticated-layout/dashboard/document/$document-id/edit"
      ]
    },
    "/_landing-layout/": {
      "filePath": "~_landing-layout.index.tsx",
      "parent": "/_landing-layout"
    },
    "/(core)/_authenticated-layout/dashboard/": {
      "filePath": "~(core)/~_authenticated-layout/~dashboard/~index.tsx",
      "parent": "/(core)/_authenticated-layout"
    },
    "/(core)/_authenticated-layout/dashboard/documents": {
      "filePath": "~(core)/~_authenticated-layout/~dashboard/~documents.tsx",
      "parent": "/(core)/_authenticated-layout"
    },
    "/(core)/_authenticated-layout/dashboard/document/$document-id/edit": {
      "filePath": "~(core)/~_authenticated-layout/~dashboard/~document/~$document-id/~edit.tsx",
      "parent": "/(core)/_authenticated-layout"
    }
  }
}
ROUTE_MANIFEST_END */
